#!/usr/bin/perl

use strict;
use warnings;

use lib 'lib';
use Kn;

# Prints a usage message and exists
sub usage {
	print STDERR "usage: $0 (-e program | -f file)\n";
	exit 1
}

my $switch = shift @ARGV;

usage unless $#ARGV == 0 && ($switch eq '-f' || $switch eq '-e');

if ($switch eq '-f') {
	Kn->run(join '', <>);
} elsif ($switch eq '-e') {
	Kn->run(shift @ARGV);
} else {
	usage;
}

